# Site settings
title: Pomodo
author: Afonso França and Thiago Sciotta
description: Our virtual portfolio.
meta_description: Software developers at all!

google_analytics_id: UA-84379893-1

# Build settings
exclude: [node_modules, package.json, npm-debug.log, gulpfile.js, scss]
repository: "pomodobot/pomodobot.github.io"
gems: [bourbon, neat]
sass:
  style: compressed